### ISSUE TITLE
Fresh node.js, Brunch, bower, and angular-brunch-seed produces TypeError: Arguments to path.join

### ISSUE THREAD

**Issue by geeklisted** [scotch/angular-brunch-seed#62]
Slightly experienced with node.js but new to Brunch and Bower.  I followed the instructions in the angular-brunch-seed README to a tee.  I grabbed the latest angular-brunch-seed from github, ran 'bower install', and then attempted to run server.sh.

I receive: error: [TypeError: Arguments to path.join must be strings]

However, I can't seem to figure out how to specify that I want a more verbose output.  I.e. a file and line number would be nice.

This is the second attempt at running this skeleton app and second time encountering this error.

I've also ran 'bower update'.  I haven't made any changes to config.coffee, package.json, or component.json.  

More information below:

myapp]$ node --version
v0.10.3

myapp]$ bower list
bower discover Please wait while newer package versions are being discovered
/web-workspace/myapp
├── angular#1.0.4 (1.0.6 now available)
├─┬ angular-cookies#1.0.4 (1.0.6 now available)
│ └── angular#1.0.4 (1.0.6 now available)
├─┬ angular-mocks#1.0.4
│ └── angular#1.0.4 (1.0.6 now available)
├─┬ angular-resource#1.0.4 (1.0.6 now available)
│ └── angular#1.0.4 (1.0.6 now available)
├─┬ angular-sanitize#1.0.4 (1.0.6 now available)
│ └── angular#1.0.4 (1.0.6 now available)
├─┬ bootstrap#2.2.2 (2.3.1 now available)
│ └── jquery#1.8.3 (1.9.1 now available)
├─┬ bootstrap-less-themes#73fcfda89ce8bc89254d50ac51864a8875285e39
│ └─┬ bootstrap#2.2.2 (2.3.1 now available)
│   └── jquery#1.8.3 (1.9.1 now available)
├── console-polyfill#a51501a90a87d895a13b7316f3b3dc7920447e9a
├── font-awesome#3.0.2
└── jquery#1.8.3 (1.9.1 now available)

**Comment by kylefinley** [comment]
@geeklisted,

Sorry that you ran into problems. There was an issue GulinSS/bower-javascript-brunch with node > 0.10. It was resolved here:

GulinSS/bower-javascript-brunch/pull/2

We're just waiting for the updated version to be pushed to npm

In the mean time you should be able to modify your `package.json` file to use master. These line:

``` json
{
    // ...
    "bower-stylesheet-brunch": "git://github.com/GulinSS/bower-stylesheet-brunch/#master",
    "bower-javascript-brunch": "git://github.com/GulinSS/bower-javascript-brunch/#master",
    // ...
}
```

I've considered change these lines in angular-brunch-seed as a temporary fix, but I think this method breaks on Windows.

Please let me know it the fixes your issue.

**Comment by geeklisted** [comment]
Kyle - thanks for the super quick reply!

Unfortunately, I'm still encountering the error.  Maybe I should install version 0.9 of node.js?  Here is what I did:

1) Updated package.json in /myapp/package.json per instructions.
2) Ran > bower cache-clean
3) Ran > bower install
4) Ran brunch w.
 a) Same TypeError: Arguments to path.join must be strings
5) Ran ./scripts/server.sh
 b) Same TypeError: Arguments to path.join must be strings

Here is a larger snippet from package.json to show the updated values per your instructions:
     // ..... continued
    "auto-reload-brunch": ">= 1.5 < 1.6",
    "uglify-js-brunch": ">= 1.5 < 1.6",
    "clean-css-brunch": ">= 1.5 < 1.6",
    "bower-stylesheet-brunch": "git://github.com/GulinSS/bower-stylesheet-brunch/#master",
    "bower-javascript-brunch": "git://github.com/GulinSS/bower-javascript-brunch/#master",
    "bower-asserts-brunch": "*",
    "bower": "~0.8.5",
    // ... continued

Thanks for your help & patience.

**Comment by geeklisted** [comment]
Kyle - Hmm, I think I got it working.  I re-ran ./scripts/init.sh and that did the trick.  Would be interesting to know from your standpoint why that would have made a difference...does it perform an uninstall and re-install of underlying packages?

Thanks, I think I'm good now.

**Comment by kylefinley** [comment]
Excellent!

Yes, `./scripts/init.sh` removes the `node_modules` directory and reinstalls them.

I'm glad that you got things working. I'm going to leave this issue open, until this is resolve.

**Comment by geeklisted** [comment]
Kyle - I did not experience this error on Mac OSX with Node.js version 0.8.16; just wanted to let you know.

Thanks.

**Comment by kylefinley** [comment]
Thanks @geeklisted, 

Yes, I believe the issue is caused by changes made in Node 0.10.x. I push a commit d9b360a4b0fa212bedc4edf084ded2efc7cdfb0b that adds the suggested edits.

Thank you for reporting this. Please let me know if you have any other issues.
